### ISSUE TITLE
Issue with multiple fragments

### ISSUE THREAD

**Issue by darcheville** [goyourfly/TabViewPager#1]
Hello,

thank you for your library and your work :),
but there is an issue : 
1) i have a header, a (tablayout and multiple fragment with recyclerview) -> tabviewpager
2) i scroll the first fragment until middle of header
<img width="85" alt="capture d ecran 2017-12-04 a 21 46 05" src="https://user-images.githubusercontent.com/7430502/33575382-b132f75c-d93c-11e7-938a-c9432e3df3df.png">
3) i press the second tab of tablayout, the second fragment appears
4) i scroll the second fragment 
5) i press again first tab to get first fragment, but the recyclerview position is at the beginning position under the tablayout
<img width="121" alt="capture d ecran 2017-12-04 a 21 44 44" src="https://user-images.githubusercontent.com/7430502/33575340-8ead8d46-d93c-11e7-8ce3-9c884d62b20a.png">

Thanks and Regards,
Darcheville

**Comment by goyourfly** [comment]
You should make the header not transparent

**Comment by darcheville** [comment]
Yeah thank you :)
